# Generated by Django 2.0.2 on 2018-05-16 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
