# Generated by Django 2.0.2 on 2018-09-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileDB', '0008_auto_20180914_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='concentration',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
