# Generated by Django 2.0.2 on 2018-05-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cogito', '0002_remove_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='destination',
            field=models.CharField(default='Home', max_length=200),
            preserve_default=False,
        ),
    ]
